### ISSUE TITLE
Update file naming and add decorators and setters/gettings

### ISSUE THREAD

**Issue by Sean-Nishi** [Sean-Nishi/M1Wengine#300]
- [x] change CamelCase to snake_case #179
- [x] add property decorators to all vars #276 
- [x] update file naming convention #148
